# Generated by Django 4.0.4 on 2022-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_contact_message_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.FileField(blank=True, default='images/defaultlogopic.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.FileField(blank=True, default='images/defaultlogopic.png', null=True, upload_to='images'),
        ),
    ]
